name: Discord通知

on:
  workflow_run:
    workflows: ['Discord Notifications']
    types:
      - completed

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Discordに結果を通知
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: |
            Discord Notifications ワークフローが ${{ github.event.workflow_run.conclusion }} で終了しました！
            リポジトリ: ${{ github.repository }}
            ブランチ: ${{ github.event.workflow_run.head_branch }}
            実行者: ${{ github.event.workflow_run.actor.login }}
            詳細: ${{ github.event.workflow_run.html_url }}
